### ISSUE TITLE
./tohex.sh problem

### ISSUE THREAD

**Issue by quantrpeter** [chadyuu/riscv-chisel-book#12]
hi, i got problem when i run ./tohex.sh. Any hints? thanks

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/eacec0be-39ef-49b5-ac0f-ff246c46f754">

**Comment by nozomioshi** [comment]
It looks like you only need to `mkdir riscv` under the folder `/src/chisel-template/src` because riscv64-unknown-elf-objcopy won't automatically create folders that do not exist.

**Comment by quantrpeter** [comment]
thank you Japanese Friend, greeting from Hong Kong
ありがとう日本の友人、香港からのご挨拶
